alias turnon='cd ~/robot_ws && source install/local_setup.bash && ros2 launch ros2_twist_message_to_robot_motion launch.py'
alias gamepad='cd ~/robot_ws && source install/local_setup.bash &&  ros2 launch ros2_gamepad_to_twist_message launch.py'
